fix

diff --git a/.github/actions/project-setup/action.yml b/.github/actions/project-setup/action.yml
--- a/.github/actions/project-setup/action.yml
+++ b/.github/actions/project-setup/action.yml
@@ -14,8 +14,23 @@ runs:
   steps:
     - uses: pnpm/action-setup@v4
       name: Install pnpm
+    - name: Setup pnpm cache
+      shell: bash
+      run: |
+        store_dir=$(pnpm store path)
+        echo "Resolved pnpm store dir: $store_dir"
+        if [ ! -d "$store_dir" ]; then
+          echo "pnpm store directory not found"
+          exit 1
+        fi
+        echo "dir=$store_dir" >> "$GITHUB_OUTPUT"
+    - name: Cache pnpm store
+      uses: actions/cache@v4
       with:
-        cache: true
+        path: ${{ steps.pnpm_store.outputs.dir }}
+        key: ${{ inputs.runs-on || runner.os }}-pnpm-store-${{ inputs.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
+        restore-keys: |
+          ${{ inputs.runs-on || runner.os }}-pnpm-store-${{ inputs.node-version }}-
     - name: Install dependencies
       shell: bash
       run: pnpm install --frozen-lockfile
